# MPLAB X generated Makefile stub
# The actual build rules live in nbproject/Makefile-*.mk

SHELL=sh
default: build

build: .build-impl
clean: .clean-impl

.build-pre:
.clean-pre:
.clobber-pre:
.all-pre:

include nbproject/Makefile-impl.mk
