# MPLAB X generated Makefile stub
# The actual build rules live in nbproject/Makefile-*.mk

SHELL=sh
default: build

build: .build-post
.build-pre:
.build-post: .build-impl
clean: .clean-post
.clean-pre:
.clean-post: .clean-impl
include nbproject/Makefile-variables.mk
include nbproject/Makefile-default.mk
